version: '3.8'

services:
  web:
    image: rozitech-saas:latest
    container_name: rozitech-web
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DATABASE_URL=postgresql://rozitech:${DB_PASSWORD}@postgres:5432/rozitech_saas
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-rozitech.com,rozitech.co.za,154.65.107.234}
      - DEBUG=False
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - logs_volume:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - rozitech-network

  postgres:
    image: postgres:15-alpine
    container_name: rozitech-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rozitech_saas
      - POSTGRES_USER=rozitech
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rozitech-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rozitech"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rozitech-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - rozitech-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: rozitech-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_conf:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - rozitech-network

  celery:
    image: rozitech-saas:latest
    container_name: rozitech-celery
    restart: unless-stopped
    command: celery -A config worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DATABASE_URL=postgresql://rozitech:${DB_PASSWORD}@postgres:5432/rozitech_saas
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - logs_volume:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - rozitech-network

  celery-beat:
    image: rozitech-saas:latest
    container_name: rozitech-celery-beat
    restart: unless-stopped
    command: celery -A config beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DATABASE_URL=postgresql://rozitech:${DB_PASSWORD}@postgres:5432/rozitech_saas
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - logs_volume:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - rozitech-network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  logs_volume:
  certbot_www:
  certbot_conf:

networks:
  rozitech-network:
    driver: bridge