# Generated by Django 4.2.24 on 2025-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='schema_name',
            field=models.CharField(blank=True, help_text='PostgreSQL schema name for tenant isolation', max_length=63, null=True, unique=True),
        ),
    ]
