# Generated by Django 4.2.24 on 2025-10-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_schema_name'),
    ]

    operations = [
        # Add TenantMixin fields to Organization
        migrations.AddField(
            model_name='organization',
            name='auto_create_schema',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_drop_schema',
            field=models.BooleanField(default=False),
        ),
        # Add tenant field to Domain (same as organization, for django-tenants compatibility)
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tenant_domains',
                to='tenants.organization'
            ),
        ),
    ]
