# Generated by Django 4.2.24 on 2025-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product_code',
            field=models.CharField(blank=True, help_text="Product code for this subscription (e.g., 'teamspace', 'insurr')", max_length=50, null=True),
        ),
    ]
